// Input Data

const rawApiData = [
    {
        id: "p-001",
        productName: "Wireless Mouse",
        category: "Electronics",
        price: 25.99,
        rating: 4.5,
        stock: 15,
    },
    {
        id: "p-002",
        productName: "The Art of Computer Programming",
        category: "Books",
        price: 20.99,
        rating: 3.5,
        stock: 20,
    },
    {
        id: "p-003",
        productName: "Cyber Hoodie",
        category: "Clothing",
        price: 80,
        rating: 4.5,
        stock: 10,
    },
    {
        id: "p-004",
        productName: "Bluetooth Speaker",
        category: "Electronics",
        price: 45.0,
        rating: 4.2,
        stock: 30,
    },
    {
        id: "p-005",
        productName: "Stainless Steel Water Bottle",
        category: "Outdoors",
        price: 19.99,
        rating: 4.7,
        stock: 50,
    },
    {
        id: "p-006",
        productName: "Yoga Mat",
        category: "Sports",
        price: 29.5,
        rating: 4.3,
        stock: 40,
    },
    {
        id: "p-007",
        productName: "LED Desk Lamp",
        category: "Home",
        price: 34.99,
        rating: 4.4,
        stock: 25,
    },
    {
        id: "p-008",
        productName: "Noise Cancelling Headphones",
        category: "Electronics",
        price: 129.99,
        rating: 4.6,
        stock: 12,
    },
    {
        id: "p-009",
        productName: "Espresso Coffee Beans (1kg)",
        category: "Grocery",
        price: 24.0,
        rating: 4.1,
        stock: 80,
    },
    {
        id: "p-010",
        productName: "Ceramic Knife Set",
        category: "Kitchen",
        price: 39.99,
        rating: 3.9,
        stock: 22,
    },
    {
        id: "p-011",
        productName: "Running Shoes",
        category: "Clothing",
        price: 75.0,
        rating: 4.0,
        stock: 18,
    },
    {
        id: "p-012",
        productName: "Smartphone Stand",
        category: "Office",
        price: 12.49,
        rating: 4.2,
        stock: 100,
    },
    {
        id: "p-013",
        productName: "Gaming Mouse Pad",
        category: "Electronics",
        price: 14.99,
        rating: 4.5,
        stock: 60,
    },
    {
        id: "p-014",
        productName: "Children's Puzzle (500 pcs)",
        category: "Toys",
        price: 18.0,
        rating: 4.0,
        stock: 35,
    },
    {
        id: "p-015",
        productName: "Organic Facial Cleanser",
        category: "Beauty",
        price: 15.99,
        rating: 4.3,
        stock: 45,
    },
    {
        id: "p-016",
        productName: "Electric Kettle",
        category: "Kitchen",
        price: 49.99,
        rating: 4.4,
        stock: 28,
    },
    {
        id: "p-017",
        productName: "Camping Hammock",
        category: "Outdoors",
        price: 59.99,
        rating: 4.6,
        stock: 14,
    },
    {
        id: "p-018",
        productName: "Wireless Charger",
        category: "Electronics",
        price: 22.5,
        rating: 4.1,
        stock: 70,
    },
    {
        id: "p-019",
        productName: "Desk Organizer",
        category: "Office",
        price: 16.0,
        rating: 3.8,
        stock: 55,
    },
    {
        id: "p-020",
        productName: "Classic Novel Set",
        category: "Books",
        price: 39.99,
        rating: 4.8,
        stock: 10,
    },
    {
        id: "p-021",
        productName: "Scented Candle (Pack of 3)",
        category: "Home",
        price: 21.99,
        rating: 4.0,
        stock: 65,
    },
    {
        id: "p-022",
        productName: "Wireless Earbuds",
        category: "Electronics",
        price: 59.99,
        rating: 4.2,
        stock: 33,
    },
    {
        id: "p-023",
        productName: "Fitness Tracker",
        category: "Electronics",
        price: 89.99,
        rating: 3.9,
        stock: 20,
    },
    {
        id: "p-024",
        productName: "Kids' T-shirt",
        category: "Clothing",
        price: 9.99,
        rating: 4.1,
        stock: 120,
    },
    {
        id: "p-025",
        productName: "Adjustable Dumbbells",
        category: "Sports",
        price: 199.0,
        rating: 4.5,
        stock: 8,
    },
    {
        id: "p-026",
        productName: "Silicone Baking Mat",
        category: "Kitchen",
        price: 11.99,
        rating: 4.6,
        stock: 46,
    },
    {
        id: "p-027",
        productName: "Portable Power Bank",
        category: "Electronics",
        price: 29.99,
        rating: 4.0,
        stock: 72,
    },
    {
        id: "p-028",
        productName: "Memory Foam Pillow",
        category: "Home",
        price: 44.99,
        rating: 4.3,
        stock: 26,
    },
    {
        id: "p-029",
        productName: "Car USB Charger",
        category: "Automotive",
        price: 8.99,
        rating: 4.1,
        stock: 150,
    },
    {
        id: "p-030",
        productName: "Stroller Organizer",
        category: "Baby",
        price: 17.99,
        rating: 4.2,
        stock: 40,
    },
    {
        id: "p-031",
        productName: "Handheld Vacuum",
        category: "Home",
        price: 69.99,
        rating: 3.7,
        stock: 15,
    },
];

//? Output Data => [{name: "Wireless Mouse"}, {name: "Bluetooth Speaker"}, ... ]

//* Process: 
//Todo: Filter => Electronics
//Todo: Sort by Rating (High to Low)
//Todo: Slice => Top 5 (first 5 items)
//Todo: Map => transform object shape to {name: productName}

const topElectronicsProducts = rawApiData.filter((item) => item.category === "Electronics")
    .sort((a, b) => b.rating - a.rating)
    .slice(0, 5)
    .map((item) => {
        return { name: item.productName }
    });

console.log(topElectronicsProducts);
